/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ViewRIERecords.java
 *
 * Created on Apr 22, 2014, 2:44:03 PM
 */

import java.sql.*;
import javax.swing.table.*;
import java.util.*;

import javax.swing.DefaultComboBoxModel;


/**
 *
 * @author irham rasyidi
 */
public class ViewRIERecords extends javax.swing.JFrame {

    Controller cont;
    ArrayList<String> categories;
    /** Creates new form ViewRIERecords */
    public ViewRIERecords( Controller cont ) throws SQLException {
        
        this.cont = cont;

        ResultSet rs = cont.getResultSet("select distinct category from records;"); 
        ResultSetMetaData rsmd = rs.getMetaData();
        int catCount = 0;
        
        categories = new ArrayList<String>(catCount+1);
        categories.add("All");
        
        while (rs.next()) {
            categories.add(rs.getString(1));
        }
 
        
        rs = cont.getResultSet("select * from records;"); 
        updateTable(rs);

        initComponents();
    
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("View RIE Records");

        jLabel1.setText("Category:");

        jComboBox1.setModel(new DefaultComboBoxModel(categories.toArray()));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Select a Category"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, 0, 412, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        int index = jComboBox1.getSelectedIndex();
        String[] queries = new String[]{
            "SELECT * FROM RECORDS;", 
            "SELECT USERID, DESC1, YEAR FROM RECORDS WHERE CATEGORY = 14;",
            "SELECT USERID, DESC1, YEAR FROM RECORDS WHERE CATEGORY = 15;",
            "SELECT USERID, DESC1, AWARD, YEAR FROM RECORDS WHERE CATEGORY = 16;",
            "SELECT USERID, DESC1, YEAR FROM RECORDS WHERE CATEGORY = 17;",
            "SELECT USERID, TITLE, DES1, YEAR FROM RECORDS WHERE CATEGORY = 18 OR CATEGORY = 19;",
            "SELECT USERID, DESC1, YEAR FROM RECORDS WHERE CATEGORY = 20;"
        };


        //updateTable( cont.getResultSet( queries[index] ) );

        if( index == 4 ) checkForDiscrepancies();

        try{
            updateTable( cont.getResultSet( queries[index] ) );
        }
        catch( Exception exp ){}

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void checkForDiscrepancies(){
        //TODO to be implemented
    }

    private void updateTable( ResultSet resultSet ){
        try{
            DefaultTableModel dtm = new DefaultTableModel(){
                @Override
                public boolean isCellEditable( int row, int column ){
                    return false;
                }
            };

            Vector<Object> nextRow = new Vector<Object>();

            int colCount = resultSet.getMetaData().getColumnCount();
            System.out.println("colCount in updateTable: " + colCount);
            
            dtm.setColumnCount(colCount);
            
            do { 
                String s;
                for( int a = 1; a <= colCount/*dtm.getColumnCount()*/; a++ ) {
                    //nextRow.add( resultSet.getString(a) ); 
                    s = resultSet.getString(a); System.out.println("#");
                    nextRow.add(s);
                }

                dtm.addRow( nextRow.toArray() );
                nextRow.clear();
            } while( resultSet.next() );

            jTable1.setModel( dtm );
            DefaultTableColumnModel dtcm = (DefaultTableColumnModel) jTable1.getColumnModel();

            for( int a = 0; a < resultSet.getMetaData().getColumnCount(); a++ ){
                dtcm.getColumn(a).setHeaderValue( resultSet.getMetaData().getColumnName(a+1) );
            }
        }
        catch( SQLException exp ){}
    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
